version: '3.8'

services:
  web:
    build: .
    container_name: procount-web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./htdocs:/var/www/html
      - ./logs:/var/log/apache2
    depends_on:
      - db
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: procount
      DB_USER: procount_user
      DB_PASSWORD: Procount2024!

  db:
    image: mysql:8.0
    container_name: procount-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword123!
      MYSQL_DATABASE: procount
      MYSQL_USER: procount_user
      MYSQL_PASSWORD: Procount2024!
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: procount-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 50M
    depends_on:
      - db

volumes:
  mysql_data:
